-- 035_customer_show_pricing_on_pm_pdf.sql
-- Per-customer flag that controls whether the PM work order PDF
-- (generated by techs at completion) includes a priced line-item
-- section. Default OFF — pricing stays hidden unless the office
-- explicitly turns it on for a given customer.

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS show_pricing_on_pm_pdf BOOLEAN NOT NULL DEFAULT FALSE;
